GET http://localhost:8080/todos
// --- put access token after Bearer (do i need a fresh one ??)
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJUazRPRUU1TVRBek5VWTBRamhCTXpZNE9EWkVNRVkxUWtWRlJFRkJRa016UkVZM05FRTJPQSJ9.eyJpc3MiOiJodHRwczovL255bmsuYXV0aDAuY29tLyIsInN1YiI6InRwOVl2UDE5czc5THhJZnZoR0NNNDB0MlNjbFRNcEgzQGNsaWVudHMiLCJhdWQiOiJodHRwczovL3RvZG9zIiwiaWF0IjoxNjA0Mzg5MTUxLCJleHAiOjE2MDQ0NzU1NTEsImF6cCI6InRwOVl2UDE5czc5THhJZnZoR0NNNDB0MlNjbFRNcEgzIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.elkuqtrWjUYq0O405O-sboE45q1-MMhm2v_JkNiRL57wYiKFrVrC-2FZfNCG4x1ymQkw_F8wLDn5dSIjtDU0IvsH6Rn3qXNgb9e4RkheDZZYrRVJaV6cqlp5hmWaPt3nCYLNYCj5lg2xV6f5-b_xR2uMlOAyzEuKV-AAkg0X5ZhEHxT9qySQohfjMdePcW1n63y8rshsFLRRUfWJ25HN-OVi3TBxdNz9_gKK80796NUBjEdJ9-CIo_XkEiidfJFmCAnAfhdi-hOb6HzEKbHIbOc1Bha_fuVrGmIovbxRUs7lUW6Pi_cSW4wvAF1ypQgz0-ICFjqgS8aAKlhXH-Nb9Q

### 

//put fresh id , check in the server console
GET http://localhost:8080/todos/2a84f2b8-37ee-405b-975c-3fbbd3c1a8c1 
// --- put access token after Bearer (do i need a fresh one ??)
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJUazRPRUU1TVRBek5VWTBRamhCTXpZNE9EWkVNRVkxUWtWRlJFRkJRa016UkVZM05FRTJPQSJ9.eyJpc3MiOiJodHRwczovL255bmsuYXV0aDAuY29tLyIsInN1YiI6InRwOVl2UDE5czc5THhJZnZoR0NNNDB0MlNjbFRNcEgzQGNsaWVudHMiLCJhdWQiOiJodHRwczovL3RvZG9zIiwiaWF0IjoxNjA0Mzg5MTUxLCJleHAiOjE2MDQ0NzU1NTEsImF6cCI6InRwOVl2UDE5czc5THhJZnZoR0NNNDB0MlNjbFRNcEgzIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.elkuqtrWjUYq0O405O-sboE45q1-MMhm2v_JkNiRL57wYiKFrVrC-2FZfNCG4x1ymQkw_F8wLDn5dSIjtDU0IvsH6Rn3qXNgb9e4RkheDZZYrRVJaV6cqlp5hmWaPt3nCYLNYCj5lg2xV6f5-b_xR2uMlOAyzEuKV-AAkg0X5ZhEHxT9qySQohfjMdePcW1n63y8rshsFLRRUfWJ25HN-OVi3TBxdNz9_gKK80796NUBjEdJ9-CIo_XkEiidfJFmCAnAfhdi-hOb6HzEKbHIbOc1Bha_fuVrGmIovbxRUs7lUW6Pi_cSW4wvAF1ypQgz0-ICFjqgS8aAKlhXH-Nb9Q

